const searchItems = [
        { name: "AP Dashboard   #Asset Protection ", url: "https://portaldoctool.cvs.com/retailportalfiles/wlm_task_reports/INFO_XXXXX.pdf" },
        { name: "Command Center  (removed due to biometric rollout) ", url: "https://storeui.rxc.cvs.com:31212/command-center/?hostname=localhost&facilityId=XXXXX&port=30000" },
        { name: "Truck Manifests  #Reports ", url: "https://portaldoctool.cvs.com/portalDocTool/viewDocuments.do?listingID=dcReportPage&roles=ZGNyZXBvcnRwYWdldXNlcg==&storeNumber=XXXXX" },
        { name: "Express Scripts PRC #Dispensing", url: "https://authsvc.cvshealth.com/idp/startSSO.ping?PartnerSpId=https://prc.express-scripts.com" },
        { name: "myReports/Spark (field) #Operational", url: "https://retailspark.cvs.com/spark?view=storeView&storeName=sXXXXXrxs" },
        { name: "Who To Call #Communications", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/oth/WHO_TO_CALL_DOCUMENT.pdf" },
        { name: "HIPAA/Disclosing Patient Information #Communications", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Disclosing_Patient_Information_Job_Aid.pdf" },
        { name: "Controlled Substance Hub (pilot) #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/CS_Hub_Pharmacist_Toolkit_Store_Version_20250326151148745.pdf" },
        { name: "Proof of Liability Insurance (COI) #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/CVS_Health_Corporation_COI_2025_20241230114942787.pdf" },
        { name: "New RTS on Ironman/storeOS Job Aid #Miscellaneous", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/RTS_on_Ironman_Job_Aid.pdf" },
        { name: "myReports/Spark (store) #Operational", url: "https://retailspark.cvs.com/spark?view=storeView" },
        { name: "Environmental Health and Safety Reports Portal #Reports", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Environmental_Health_%26_Safety_Reports_Portal_Job_Aid.pdf" },
        { name: "TempAlert/SmartSense Single Sign On (SSO) #Operational", url: "https://app.smartsense.co/api/Saml/InitiateSingleSignOn/CVS?returnUrl=https://app.smartsense.co/start/XXXXX" },
        { name: "TempAlert/SmartSense (generic/store login) #Operational", url: "https://app.smartsense.co" },
        { name: "Pet Med Formulary #Pet Med/CF/SPAR", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Did_you_know_20250310152951196.pdf" },
        { name: "Pet Med Indications for Preventatives #Pet Med/CF/SPAR", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Preventives_Indications_Chart_20250311122103610.pdf" },
        { name: "Pet Med Rebates #Pet Med/CF/SPAR", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Pet_Med_Rebate_20250317085858808.pdf" },
        { name: "Pet Med Quick Tips #Pet Med/CF/SPAR", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Pet_Meds_Colleague_Quick_Tips_20250220101023926.pdf" },
        { name: "Pet Med Training #Pet Med/CF/SPAR", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Pet_Meds_Training.pdf" },
        { name: "Pet Med Readiness Checklist #Pet Med/CF/SPAR", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Pet_Meds_Store_Readiness_Checklist.pdf" },
        { name: "Chain Launcher (JNLP) #IT Resources", url: "https://jnlplauncher.rxc.cvs.com:7289/RxConnectRxP/" },
        { name: "Citrix #Operational", url: "https://appsmcsaml.corp.cvscaremark.com/" },
        { name: "myDocs #Operational", url: "https://storeresources.cvsapps.com/?user_ard=MTYzMQ==&employee_ID=MjI2Nzg0Nw==&user_firstname=R2VuZXJpYyBteURvY3M=&user_lastname=QWNjb3VudA==&user_title=UGhhcm1hY2lzdA==" },
        { name: "Store Supplies #Operational", url: "/rxnet/storesupplies" },
        { name: "Outlook #Operational", url: "https://mail.cvshealth.com/" },
        { name: "Apps Portal ", url: "https://apps.cvshealth.com/logon/LogonPoint/tmindex.html" },
        { name: "Ariba ", url: "https://s1.ariba.com/Buyer/Main/aw?awh=r&awssk=zzWQVycDkiqf98cE&realm=CVS-P2P&awrdt=1" },
        { name: "UpToDate #Clinical", url: "https://www.uptodate.com/contents/search" },
        { name: "Clinical Pharm #Clinical", url: "https://www.clinicalkey.com/pharmacology/" },
        { name: "Micromedex #Clinical", url: "https://www.micromedexsolutions.com/micromedex2/librarian/" },
        { name: "DailyMed #Clinical", url: "https://dailymed.nlm.nih.gov/dailymed/" },
        { name: "DynaMed #Clinical", url: "https://www.dynamed.com" },
        { name: "Pharmacist's Letter Access Job Aid #Miscellaneous", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Pharmacists_Letter_access_jobaid_20220415095427755.pdf" },
        { name: "Contraceptive Sub #Clinical", url: "https://pharmacist.therapeuticresearch.com/Content/Segments/PRL/2015/Jul/Comparison-of-Oral-Contraceptives-and-Non-Oral-Alternatives-United-States-8631" },
        { name: "Do Not Crush List #Clinical", url: "https://pharmacist.therapeuticresearch.com/Content/Segments/PRL/2014/Aug/Meds-That-Should-Not-Be-Crushed-7309" },
        { name: "All Clinical References #Clinical", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/ClinicalResourceGuide_20230207125446867.pdf" },
        { name: "Cardinal #Filling", url: "https://www1.cardinalhealth.com/" },
        { name: "Rx Phone Order #Dispensing", url: "/rxnet/docs/rxtelephonev2.pdf" },
        { name: "Rx Transfer #Dispensing", url: "/rxnet/docs/rxtransferv2.pdf" },
        { name: "Image Retrieval Tool **refresh the page if it loads with an error**   #Dispensing", url: "https://rxdw-rximageretrieval.rxdw-cld-ap.cvshealthcloud.com/imageRequest#no-back-button" },
        { name: "Formulary #Inventory", url: "/rxnet/formulary" },
        { name: "iPledge #Dispensing", url: "https://ipledgeprogram.com/?connection=cvs" },
        { name: "Syringes/Needles #Inventory", url: "/rxnet/syringes" },
        { name: "SIG Code Sheet #Dispensing", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/RxConnect_SIG_Codes_Best_Practices.pdf" },
        { name: "Nebulizers/Spacers (Legacy - alt) #Dispensing", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Nebulizer_and_Spacer_Support_RxNet_Page_KP_20210618153949167.pptx_2pdf.pdf" },
        { name: "Naloxone #Dispensing", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Naloxone_Program_Support_Page_20240102165341901.pdf" },
        { name: "McKesson #Inventory", url: "https://connect.mckesson.com/content" },
        { name: "PEG Formulations #Inventory", url: "/rxnet/pegforms" },
        { name: "mySchedule (formerly myWork -- search Zipline for new task management portal) #Operational", url: "https://cvs.reflexisinc.com/kernel/views/authenticate/web/CVS.view" },
        { name: "My Customer Connection (MCC)  #Communications", url: "https://cvs.medallia.com/sso/cvs" },
        { name: "LearningHub #Training", url: "https://cvshealth.sabacloud.com/" },
        { name: "Remote Training Approval aka RRT  #Training", url: "https://app-corp-rewrite-prod-use2-web.azurewebsites.net/rrtAccessManagement" },
        { name: "Workbrain #Manager", url: "https://cvs.cloud.infor.com/" },
        { name: "Service Channel #Manager", url: "https://authsvc.cvshealth.com/idp/startSSO.ping?PartnerSpId=https://login.servicechannel.com" },
        { name: "DL Store Visit Tool (SVT)  #Manager", url: "https://svt.cvsapps.com/sso" },
        { name: "Attendance Tracker #Manager", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Attendance_Tracker_7.2018__20180731161449175.pdf" },
        { name: "Print Name Tag Labels #Manager", url: "https://nametagger.cvs.com" },
        { name: "Payroll/Timekeeping Job Aid   #Manager", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Store_Leader_Payroll_SOP_Feb_2025_vF_20250214120945448.pdf" },
        { name: "Workday #Human Resources", url: "https://www.myworkday.com/cvshealth/d/home.htmld" },
        { name: "ColleagueZone #Human Resources", url: "https://colleaguezone.cvs.com" },
        { name: "Heartbeat #Human Resources", url: "https://stores.heartbeat.cvshealth.com/" },
        { name: "Hiring Support #Human Resources", url: "https://colleaguezone.cvs.com/cz?id=sc_cat_item&table=sc_cat_item&sys_id=ee91566efb81a69026f7f2b455efdc0a&recordUrl=com.glideapp.servicecatalog_cat_item_view.do%3Fv%3D1&sysparm_id=ee91566efb81a69026f7f2b455efdc0a" },
        { name: "Multi-factor authentication (Legacy link)  #Human Resources ", url: "https://idmgmt.cvshealth.com/iam-selfserviceportal-oci/home" },
        { name: "Attendance Policy and Logs #Human Resources", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0058118" },
        { name: "Hiring Guide #Human Resources", url: "https://colleaguezone.cvs.com/cz?id=kb_article_view&sysparm_article=KB0061720" },
        { name: "COVID Sick Policy #Human Resources", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0059260" },
        { name: "Concur Payouts #Human Resources", url: "https://federatione.cvshealth.com/affwebservices/public/saml2sso?SPID=p0089280mxzg" },
        { name: "Meal Break Waiver #Human Resources", url: "https://colleaguezone.cvs.com/cz?id=sc_cat_item&sys_id=3a46341d1be5d598f839caae6e4bcbc5" },
        { name: "Incident/Error Reporting #Regulatory", url: "https://epso.corp.cvscaremark.com/EPSO_PROD/Infocenter/Client/InfoPageIndex.aspx" },
        { name: "PA PDMP #Regulatory", url: "https://pennsylvania.pmpaware.net/" },
        { name: "NPI Registry #Regulatory", url: "https://npiregistry.cms.hhs.gov/search" },
        { name: "PALS Portal  #Regulatory ", url: "https://pals.pa.gov" },
        { name: "Store Licenses #Regulatory", url: "https://wa-licensesrep-ui-prod1.ase-usc-otia-licenserep-prod-v3.appserviceenvironment.net" },
        { name: "Pennsylvania Code #Regulatory", url: "https://www.pacodeandbulletin.gov/Display/pacode?file=/secure/pacode/data/049/chapter27/chap27toc.html&d=reduce" },
        { name: "Print TempAlert Log #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Printing_Twice_Daily_Temperature_Logs.pdf" },
        { name: "StrongPak Label #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Single_Tote_Hazardous_Waste_Label_PHARMACY__20200522125334240.pdf" },
        { name: "MethCheck #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/MethCheck_20230103130702122.pdf" },
        { name: "Patient Care Central (PCQ) #Communications", url: "https://storepcc.rxc.cvs.com:30491/pccui/v1/#/OpportunitiesList/" },
        { name: "Patient Care Central (PCQ) Local Link #Communications", url: "https://storepcc.rxc.cvs.com:30491/pccui/home.html?hostname=localhost&store=XXXXX&port=30000&session=1&wks=wks10" },        
        { name: "Main Directory #Communications", url: "/rxnet/directory" },
        { name: "Transfer Directory #Communications", url: "/rxnet/transfer" },
        { name: "Store Locator #Communications", url: "https://www.cvs.com/store-locator/landing" },
        { name: "Prescriber Request QR Codes #Communications", url: "/rxnet/docs/prqrcodes.pdf" },
        { name: "ThinkLP (myProfessional Practice)  #Asset Protection ", url: "https://cvsthinklp.lightning.force.com" },
        { name: "Operational Excellence Playbook #Asset Protection", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/2023_RX_AP_Operational_Excellence_Playbook_20230620135623197.pdf" },
        { name: "Operational Risk Full Guide #Asset Protection", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/myShrink_Responsibility_Operational_Risk_Guide_-_Feb_2023_20230223095053563.pdf" },
        { name: "High Risk Drugs #Asset Protection", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/High_Risk_Drug_Profiles_-_Q4_FINAL_%28updated_Nov_2022%29_20230320171225743.pdf" },
        { name: "ICAP Job Aid #Asset Protection", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/ThinkLP_ICAPs_Guide_20241009105750305.docx_2pdf.pdf" },
        { name: "SafetyHub #Asset Protection", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/rpt/mySafetyHub.pdf" },
        { name: "Cardinal/OV Order Issues #Asset Protection", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/OV_Shortage_Job_Aid_March_2026_20260309142630156.pdf" },
        { name: "eBOH Job Aid #Asset Protection", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/eBOH_Update_20230616112533749.pdf" },
        { name: "Immunization Dashboard #Immunizations ", url: "https://imzdash.rxc.cvs.com:31213/immunization/" },
        { name: "CDC Vaccine Schedules #Immunizations", url: "https://www.cdc.gov/vaccines/hcp/imz-schedules/index.html" },
        { name: "Vaccine QR Codes #Immunizations", url: "/rxnet/imzndcs" },
        { name: "Immunization Protocols #Immunizations", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/IMZ_Resource_Center_State_pages_20230531143412947.pdf" },
        { name: "Immunization Ordering Guide  #Immunizations ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Immunization_Program_Ordering_Guide_Expanded_Vaccines_20190318112807758.pdf" },
        { name: "Immunization Inventory Tool Job Aid  #Immunizations ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Immunization_Inventory_Tool_Job_Aid_20240614123353339.pdf" },
        { name: "Immunization Pharmacist Curriculum  #Immunizations ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Pharmacist_and_Intern_Immunization_Curriculum_20220720144842710.pdf" },
        { name: "Immunization Technician Curriculum  #Immunizations ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Pharmacy_Technician_Immunization_Curriculum_2022062814253156.pdf" },
        { name: "Uploading Certifications  #Immunizations ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Colleague_Self_Entry_of_Required_Immunization_Certificates_and_CPR_2023072713230237.pdf" },
        { name: "NABP CE ID #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/NABP_e-Profile_ID__20251031144708533.pdf" },
        { name: "CPR Scheduling Job Aid #Immunizations  ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/CPR_Job_Aid_for_Store_Colleagues_20240223155128952.pptx_2pdf.pdf" },
        { name: "Travel Immunization NDCs #Immunizations  ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/TravelVaccineDetails_20241106120156848.pdf" },
        { name: "Travel Immunization Reference  #Immunizations ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Travel_IMZ_Cheat_Sheet_12122024_20241212111427361.docx_2pdf.pdf" },
        { name: "CDC Yellow Book  #Immunizations ", url: "https://wwwnc.cdc.gov/travel/page/yellowbook-home" },
        { name: "Store Digest #Reports", url: "https://retailspark.cvs.com/rbi/?options-base=on&storeNumber=" },
        { name: "Queue Depth #Reports", url: "https://rxcreports.rxc.cvs.com:31210/airsupport/queuesummary" },
        { name: "CIIM  #Reports", url: "https://ciim.cvs.com/ciimappnew/#/login" },
        { name: "Rx Scoreboard (Legacy) #Reports", url: "/rxnet/docs/scoreboard.pdf" },
        { name: "Profit & Loss #Reports", url: "https://enterpriseportalreporting-prd2.corp.cvscaremark.com:8443/enterprisePortalReporting/viewDocuments.do?listingID=storeProfitLoss&roles=c3RvcmVwbHVzZXI=&storeNumber=XXXXX" },
        { name: "Green Sheets #Reports", url: "https://enterpriseportalreporting-prd2.corp.cvscaremark.com:8443/enterprisePortalReporting/viewDocuments.do?listingID=fmsGreenSheetsReportLandingPage&roles=Zm1zcG9ydHBhZ2V1c2Vy&storeNumber=XXXXX" },
        { name: "Compliance Report Job Aid #Reports", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/LearningHub_Analytics_MyTeam_Compliance_Reporting_2023062113415949.pdf" },
        { name: "To-Do List Report #Reports", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/oth/LearningHub_Analytics_MyTeam_To-Do_List_Reporting.pptx_2pdf.pdf" },
        { name: "OA Audit Appeals Portal ", url: "https://www.cvsreports.com/RXRC/CorporateHome" },
        { name: "Onboarding #New Hires ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/oth/New_Colleague_Onboarding_Welcome_Guide.pdf" },
        { name: "NCO Packet #New Hires ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/NCO_Participant_Guide_20230524153648944.pdf" },
        { name: "NCO Shift 1 Guide  #New Hires   ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Trainee_Guide_Shift_1_20230512173831874.pdf" },
        { name: "LearnRx Main Page  #New Hires ", url: "https://cvshealth.sabacloud.com/Saba/Web_spf/NA10P1PRD006/app/shared;spf-url=pages%2Fpagedetailview%2Fspage000000000006982%2Flearnrx-2.0%2Fresourcesz" },
        { name: "PTCB Workspace  #Training", url: "https://cvshealth.sabacloud.com/Saba/Web_spf/NA10P1PRD006/app/shared;spf-url=pages%2Fpagelistview%2Fpgcnt000000000537180" },
        { name: "NCO Checklist   #New Hires  ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/New_Colleague_Onboarding_Checklist_20230525160346735.pdf" },
        { name: "POS Profile Creation  #New Hires ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/rpt/POS_Profile_Creation_Guide.pdf" },
        { name: "SPAR RTS Job Aid #Pet Med/CF/SPAR  #Specialty", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/SPAR_-_RTS_Guide_20230815_20230815163603433.pdf" },
        { name: "SPAR Check-in  #Pet Med/CF/SPAR  #Specialty ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/SPAR_-_Checkin_and_Checkout_Process.20240130.pptx_2pdf.pdf" },
        { name: "SPAR Quick Ref   #Pet Med/CF/SPAR  #Specialty", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Specialty_Connect_Quick_Reference_Guide_20230227_20230227141506539.pdf" },
        { name: "SPAR Notifications  #Pet Med/CF/SPAR  #Specialty", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/SPAR_Delivery_Notification_August_2024_20240805093958712.pdf" },
        { name: "CF Resources  #Pet Med/CF/SPAR  #Central Fill ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Central_Fill_RxNet_Landing_Page.pdf" },
        { name: "Central Fill Job Aid #Pet Med/CF/SPAR  #Central Fill ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Central_Fill_Job_Aid_2023041014350208.pdf" },
        { name: "CF Check-In  #Pet Med/CF/SPAR  #Central Fill", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Central_Fill_Package_and_CheckIn_Instructions_20230410143439745.pdf" },
        { name: "CF Maintenance   #Pet Med/CF/SPAR  #Central Fill", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Central_Fill_Prescription_Maintenance_20230410143354198.pdf" },
        { name: "Barcode Generator #IT Resources", url: "https://barcode.tec-it.com/en/GS1QRCode?data=" },
        { name: "RxC Chain Launcher #IT Resources", url: "https://chainlauncher.rxc.cvs.com:7188/Launcher/AppLauncher.jnlp" },
        { name: "Device Management #IT Resources", url: "https://supportlink.stores.cvs.com/" },
        { name: "My Password Reset #Human Resources", url: "http://mypassword.cvs.com/" },
        { name: "SabaCloud #IT Resources", url: "https://cvshealth.sabacloud.com/Saba/Web_spf/NA10P1PRD006/app/me/myfiles;spf-url=common%2Fprofile%2Fmyfiles%2Femplo000000000082945" },
        { name: "Text Editor Online #IT Resources", url: "https://www.rephrase.info/online-text-editor" },
        { name: "Apps/Websites/IT Tips and Tricks #IT Resources", url: "/rxnet/usefulapps" },
        { name: "EPIC Access #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/httpsportaldoctool.cvs.comretailportalfilesradar_storetempstoreAccess_job_aid_20230906150438280.docx.pptx_2pdf.pdf" },
        { name: "EPIC Web #COVID", url: "https://rtl-hsweb.corp.cvscaremark.com/HSWeb_PRD/" },
        { name: "EPIC Playground #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/EPIC_Playground_Step_by_step_guide_April_2024_Final_20240429151804921.pdf" },
        { name: "Playground Logins #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Practice_Environment_Login_Credentials.xlsx_2pdf.pdf" },
        { name: "Symantec VIP #IT Resources", url: "https://viptfaeast.cvs.com/" },
        { name: "SalesForce Cloud ", url: "https://cvsthinklp.lightning.force.com/lightning/o/ContentDocument/home" },
        { name: "Date Calculator #Miscellaneous", url: "https://www.calculator.net/date-calculator.html" },
        { name: "Pick N Pack  #Miscellaneous ", url: "https://cvsstore.cvs.com/app/deliveryprepapp/" },
        { name: "RxDelivery Home", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/oth/RxDelivery_Resource_Center.pdf" },
        { name: "Policy/Procedure ", url: "https://policy.corp.cvscaremark.com/pnp/faces/home.xhtml" },
        { name: "CE Tracking  ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/RPh_Letter_Updated.pptx_2pdf.pdf" },
        { name: "Waiting Bin Inventory Schedule 2026", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/2026_Waiting_bin_inventory_dates_20251210093144638.docx_2pdf.pdf" },
        { name: "OTC Syringe Sales ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/OTC_Syringe_Spreadsheet_Master_20210519141310407.pdf" },
        { name: "RPh Daily Task List ", url: "https://cvshealth.sabacloud.com/Saba/document/NA10P1PRD006/simrs000000000025831" },
        { name: "Expanded Services #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/RPh_prescribing_myDocs_State_Specific_resources_11.23_2023111612555506_20231116132148708.pptx_2pdf.pdf" },
        { name: "Non-saleable Return #Miscellaneous", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Non_Saleable_Non_CII_Drugs_v2024_11_20241105124655549.pdf" },
        { name: "NIOSH Drugs #Miscellaneous", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/NIOSH_DRUGS_20191203083207826.pdf" },
        { name: "Card on File #Miscellaneous", url: "https://www.cvs.com/epp/remote-payment" },
        { name: "Insurance Tips #Dispensing", url: "/rxnet/insurancetips" },
        { name: "PA Medicaid PDL ", url: "https://papdl.com/preferred-drug-list" },
        { name: "Vaccine Medical Billing Tips", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Vaccine_Third_Party_Billing_Job_Aid_20241004132831656.pdf" },
        { name: "Pennsylvania (PA) Technician Protocol #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/PA_Pharmacy_Technician_Protocol_Sign_Off_20180730151841166_20221118092028383.pdf" },
        { name: "Nondiscrimination #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/NondiscriminationandAccessibilityNotice_CVSPharmacy_Final_Final_20170110140230949.pdf" },
        { name: "Notice of Privacy Practice (NOPP-English) #Required Docs ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/2087_7-25_Remediated_with_NOA_20250827153246920.pdf" },
        { name: "Notice of Privacy Practice (NOPP-Spanish)  #Required Docs ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/2087_SP_7-25_Remediated_with_NOA_20250827153218407.pdf" },
        { name: "Top 25 Generics #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Top_25_Generic_Drugs_June2021_20210617145343156_2022111809252190.pdf" },
        { name: "HIPAA Posting #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/PA_Notice_of_Privacy_Practices_20221118092203526.pdf" },
        { name: "PDMP Posting #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/PA_PDMP_Patient_Notice_Poster_20160715144512221.pdf" },
        { name: "Records Sign #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/record_storage_sign.pdf" },
        { name: "Medicare (English) #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Pharmacy_Notice_CMS_10147_508ed_03_04_2022_20220328090555137.pdf" },
        { name: "Medicare (Spanish) #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Pharmacy_Notice_CMS_-10147SPANISH_03_04_2022_508.doc_20220328095050763_20230330153114502.pdf" },
        { name: "Discrimination Addendum Posting #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Retail_-_CVS_Pharmacy_Non-Discrimination_Notice_2024102214163535.pdf" },
        { name: "Emergency Procedure 1-pager #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Retail_EPP_Summary_English.pdf" },
        { name: "Prescribing Job Aid #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Paxlovid_updated_jobaid_20230920105619983.pdf" },
        { name: "General Workflow #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/OAV_Digital_Workflow.pptx_2pdf.pdf" },
        { name: "Printing EPIC Docs #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Printing_receipts_and_POS_Barcode_in_Epic1-_updated_2023032910281489.pdf" },
        { name: "eGFR Calculator #COVID", url: "https://www.davita.com/tools/gfr-calculator" },
        { name: "Paxlovid Billing Job Aid #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Commercial_Paxlovid_Paxcess_Job_Aid.pdf" },
        { name: "EPIC Help #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/EPIC_Troubleshooting_Guide__2024.pdf" },
        { name: "EPIC Reference #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Test_to_Treat_Epic_Job_Aid_V1.pdf" },
        { name: "Quidel Guide #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/RX_POCT_Quidel_Training_Video_Module_Guide.pdf" },
        { name: "Quidel Manual #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/RX_POCT_Lab_Manual_V1.pdf" },
        { name: "Quidel Quality Control Log #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/RX_POCT_Quidel_Sofia_2_Covid_%2B_Flu_A_%26_B_Quality_Control_Log.pdf" },
        { name: "Retail Testing Initiatives #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/store/oth/myDocs_Homepage_COVID19PFeb25.pdf" },
        { name: "Training Roadmap #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/POST_PHE_Training_Roadmap_Point_of_Care.pptx_2pdf.pdf" },
        { name: "COVID Test Billing Job Aid #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/COVIDTesting_Billing_Job_Aid_v5.pdf" },
        { name: "COVID Testing Training Report #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Quidel_COVIDFlu_Testing_Reporting.xlsx" },
        { name: "COVID Testing Office Hours #COVID", url: "https://outlook.office365.com/owa/calendar/COVID19POCTOfficeHours@bookings.cvshealth.com/bookings/" },
        { name: "OTC COVID Test Kits #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/COVID_OTC_Test_RxNet_Page.pdf" },
        { name: "OTC COVID Kit Template with QR Codes #COVID", url: "/rxnet/docs/otckitqrtemplate.pdf" },
        { name: "COVID Vaccine Returns Job Aid #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/COVID-19_Monovalent_Product_Damage_Guide_20231003143049173.pdf" },
        { name: "Pfizer COVID Vaccine Comirnaty Quick Reference  #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Pfizer_2025.2026_COVID_Vaccine_20250827205127481.pdf" },
        { name: "Moderna COVID Vaccine Spikevax Quick Reference  #COVID ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Moderna_2025.2026_COVID_Vaccine_20250827205746158.pdf" },
        { name: "COVID Vaccine Screening Questions/Guide #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/COVID_2025-26_Health_Screener_RPh_Answer_Guide_20250820170919183.docx_2pdf.pdf" },
        { name: "COVID Vaccine CDC Guidelines  #COVID", url: "https://www.cdc.gov/vaccines/covid-19/clinical-considerations/interim-considerations-us.html" },
        { name: "Magic Mouthwash Order Set #Compounding", url: "/rxnet/docs/mmworderset.pdf" },
        { name: "Beyond Use Date (BUD) Guide #Compounding", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Beyond_Use_Dating_Guidance_20230308162552228_2023031320045034.pdf" },
        { name: "Compounding Corner #Compounding", url: "https://storeresources.cvsapps.com/?user_ard=MTYzMQ==&employee_ID=MTA5Mzk5MQ==&user_firstname=TWF0dGhldw==&user_lastname=U3RhdGhpcw==&user_title=UGhhcm1hY2lzdA==" },
        { name: "Master Formulations   #Compounding ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Master_Formulation_Landing_Page_20230509133428779.pdf" },
        { name: "Blank Compounding Log #Compounding", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Blank_Compound_Log_20230725121319464.pdf" },
        { name: "Blank Compounding Master Form #Compounding", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Create_Your_Own_Master_Formulation_20230509131316358.pdf" },
        { name: "FillMaster Cleaning #Compounding", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Monthly_FLAVORx_Auto_Maintenance_Guide_%28002%29_20221115143635353.pdf" },
        { name: "General Cleaning  #Compounding ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Compounding_Space_Cleaning_and_Maintenance_20231020164309842.pdf" },
        { name: "FillMaster Flavoring #Compounding", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Dispensing_with_the_FLAVORx_Auto_%28002%29_20240104125806446.pdf" },
        { name: "Labeling Guide  #Compounding ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Nonsterile_Compounding_Labels_20230607140522602.pdf" },
        { name: "Combpounding Binder #Compounding", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Compounding_Binder_Guidance_Document_20230801144052106.pdf" },
        { name: "First Kit Quarantine #Compounding", url: "https://cvsthinklp.my.salesforce.com/sfc/p/36000001HXbW/a/Kf000000uNSU/Pa5A628WahrLlMBtccYeZ1SasnMXokr_4S018Q2s8L0" },
        { name: "Citrix (manual login with CID) ", url: "https://appsmc.minclinic.local/Citrix/appsmcWeb/" },
        { name: "DynaMedex #Clinical", url: "https://www.dynamedex.com" },
        { name: "Clinical Key (MSU Students)", url: "https://auth.elsevier.com/ShibAuth/institutionLogin?appReturnURL=https%3A%2F%2Fwww.clinicalkey.com%2Fshibboleth%2F&entityID=urn%3Amace%3Aincommon%3Amsu.edu" },
        { name: "Pharmacist Letter #Clinical", url: "https://pharmacist.therapeuticresearch.com/Home/PL/?referer=cvs/desktop.urls" },
        { name: "Plumbs Veterinary #Clinical", url: "https://www.plumbsveterinarydrugs.com/" },
        { name: "Nebulizers/Spacers (Legacy) ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Nebulizer_and_Spacer_Support_JobAid_20240822_20240909140443539.pdf" },
        { name: "McKesson #Inventory", url: "https://connect.mckesson.com/content" },
        { name: "ColleagueZone #Human Resources", url: "https://colleaguezone.cvs.com/cz?id=favorites_list" },
        { name: "Meal Break Waiver Job Aid #Human Resources", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0061084" },
        { name: "Hiring Guide ", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0066828" },
        { name: "Hiring Dashboard ", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0066834" },
        { name: "Open a Req in Workday", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0066873" },
        { name: "Interviewing ", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0066901" },
        { name: "Offer Submission ", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0066914" },
        { name: "Background Check ", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0066902" },
        { name: "Onboarding/NCO ", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0066876" },
        { name: "I-9 Verification   ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/I-9_Reimagine_20250127193223967.pdf" },
        { name: "Contacts (Hiring) ", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0066896" },
        { name: "Time Off Balance ", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0060872" },
        { name: "Write-up Job Aid ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/WorkdayCorrectiveAction_20230914145545712.pdf" },
        { name: "Termination Job Aid ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/WorkdayTerminateColleague_20230914150959983.pdf" },
        { name: "Employee Transfer ", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0061038" },
        { name: "Annual Reviews ", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0063994" },
        { name: "Comp Plan Job Aid ", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0064270" },
        { name: "MethCheck #Regulatory", url: "https://methcheck.appriss.com/" },
        { name: "Pennsylvania Code ", url: "https://www.dos.pa.gov/ProfessionalLicensing/BoardsCommissions/Pharmacy/Pages/Board-Laws-and-Regulations.aspx" },
        { name: "DEA# Algorithm ", url: "https://ptcbtestprep.com/what-are-dea-numbers/" },
        { name: "Controlled Substances Resource Page #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Controlled_Substance_Resource_Page_Store.pdf" },
        { name: "Emergency Fills ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Providing_an_Emergency_Refill_in_Pennsylvania_20180424111233144.docx_2pdf.pdf" },
        { name: "Record Retention Requirement #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/State_Reference_Onsite_Retention_Requirements__Waivers_-_03.13.2024_20240318112804142.pdf" },
        { name: "Records Packaging ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Record_Boxing_Job_Aid_3.2023_20240326110853954.pdf" },
        { name: "Records Job Aid ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Proper_Storage_of_Confidential_Records_20221125115322488.pdf" },
        { name: "MethCheck Job Aid ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/MethCheck_Overview_and_Portal_Access_20240830152909613.pptx_2pdf.pdf" },
        { name: "Regulatory Review Job Aid ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/PM_Reg_Review_Store_Job_Aid_2023112413070971.pptx_2pdf.pdf" },
        { name: "Drug Disposal #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Drug_Disposal_Electronic_Recordkeeping_Job_Aid_-_FINAL_5.26.2026_20260527124609311.pdf" },
        { name: "Emergency Procedure Packet #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Retail_EPP_Printable_English.pdf" },
        { name: "Immunization Patient Considerations ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Beyond_the_Basics_Expanded_Vaccine_Topics_for_Pharmacists_20240911154235709.pdf" },
        { name: "Immunization Registry #Immunizations", url: "https://authsvc.cvshealth.com/idp/startSSO.ping?PartnerSpId=https%3A%2F%2Fpoct-sso.stchome.net%2Fauth%2Frealms%2Fimmslink" },
        { name: "Warehouse Backorders ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Back_Order_Rpt.pdf" },
        { name: "WeCare Weekly #Reports", url: "https://portaldoctool.cvs.com/rxreports/wecare/weekly/WeCare_Scorecard_SXXXXX.pdf" },
        { name: "WeCare Hourly #Reports", url: "https://dashboard.rxc.cvs.com:33210/WeCare/?store_id=Y3Zzd2VibWFzdGVy&roleType=Y29ycA%3D%3D" },
        { name: "LearnRx Playbook ", url: "https://cvshealth.sabacloud.com/Saba/document/NA10P1PRD006/simrs000000000022200" },
        { name: "LearnRx Detailed ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/LearnRx_2.0_Detail_Shift_View_20230525160710219.pdf" },
        { name: "Central Fill FAQs #Pet Med/CF/SPAR ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/store/oth/Central_Fill_FAQs.pdf" },
        { name: "Google Translate ", url: "https://translate.google.com/?sl=en&tl=es&op=translate" },
        { name: "Immunization Clinic IT Guide    #IMZ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/IMZ_Clinic_NTID_VPN_and_IT_Equipment_Job_Aid.pdf" },
        { name: "Opill Contraceptive ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Opill_HandoutRx_2024012910540322.pdf" },
        { name: "Calls in Queue Homepage ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Calls_in_Queue_Homepage.pdf" },
        { name: "Mifepristone #Dispensing", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/MifeprexRetailDispensingJobAid_20240306103911611.pdf" },
        { name: "Grad Intern Program ", url: "https://cvshealth.sabacloud.com/Saba/document/NA10P1PRD006/simrs000000000025922" },
        { name: "CVS Savings Finder ", url: "https://spmfinder.corp.cvscaremark.com:32513/navigator/" },
        { name: "GoodRx ", url: "https://www.goodrx.com/" },
        { name: "Manufacturer Coupons ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Manufacturer_Coupon_myDoc_Colleague_Link.pdf" },
        { name: "Executive Order 14026 #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Federal_Minimum_Wage_for_Contractors_Under_Executive_Order_14026_%282025%29_20250124122659281.pdf" },
        { name: "Executive Order 13658 #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Federal_Minimum_Wage_for_Contractors_Under_Executive_Order_13658_%282025%29_20250124122550566.pdf" },
        { name: "Paxlovid Counseling Points #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Paxlovid_Key_Counseling_Points_20220726070517444.pptx_2pdf.pdf" },
        { name: "Paxlovid Prescribing FAQs #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Paxlovid_Prescribing_In-Store_FAQ.docx_2pdf.pdf" },
        { name: "EPIC Reference COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/RxPOC_SA25_EPIC_Workflow_Job_Aid_Field_v3.pdf" },
        { name: "COVID Testing Playbook #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Post_PHE_Rph_Led_POCT_SOP_Lumira_Drive_Thru_Model.pdf" },
        { name: "COVID Testing General Resources #COVID ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/store/oth/myDocs_Homepage_COVID19PFeb25.pdf" },
        { name: "COVID Testing IronMan Job Aid #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/HAIKU_Job_Aid-_dec_2022_20221219173328749.pdf" },
        { name: "Lumira Quality Control Log #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/LumiraDx_Control_Log_20221128114939634.pptx_2pdf.pdf" },
        { name: "COVID Testing Swabbing Directions #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Lumira_English_Swab_Instructions_20210205083258874_20220526134317252.pdf" },
        { name: "COVID Testing Safety Checklist #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/COVID-19_Testing_Safety_Checklist.docx_2pdf.pdf" },
        { name: "Lumira Reference #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Lumira_Quick_Reference_Guide_20220526132557639.pdf" },
        { name: "Point of Care Testing (POCT) Homepage #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Point_of_Care_Testing_%28POC%29.pdf" },
        { name: "COVID Testing Billing Guide #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Billing_Resource_Guide_COVID_20211220135315473.pptx_2pdf.pdf" },
        { name: "COVID Vaccine FAQs  #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Combined_FAQ_20220311135851198.pdf" },
        { name: "Compounding Competency Evaluation #Compounding", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Nonsterile_Compounding_Competency_Evaluation_20230608160950128.pdf" },
        { name: "Mini Game  #Easter egg ", url: "https://colleaguezone.cvs.com/cz?id=34534" },
        { name: "Immunization Training and Protocol Homepage   #Immunizations ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/IMZ_Training_Resource_20240829_20240830093611879.pdf" },
        { name: "Compounding Workflow Guide #Compounding", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Compounding_Workflow_20230811154151986.pdf" },
        { name: "Pet med list and indication guide   ##Pet Med/CF/SPAR  ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Quick_Med_List_and_Indication_Guide_.pdf" },
        { name: "Auxillary Service Notice ACA 1557 #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Auxiliary_Service_Notice_ACA_1557_VF_2025061111454668.pdf" },
        { name: "Store Supply Barcode Quick Reference #Operational", url: "/rxnet/docs/store%20supply%20barcodes%20for%20backroom%20posting.pdf" },
        { name: "Chain Launcher (Legacy - Edge or Internet Explorer browser required) ", url: "https://chainlauncher.rxc.cvs.com:7188/Launcher/Chain.do" },
        { name: "Citrix (local MinuteClinical environment only) ", url: "https://appsmc.minclinic.local/Citrix/appsmcWeb/" },        
        { name: "MCP Spotlight #Reports", url: "https://portaldoctool.cvs.com/retailbireports/msh/mcp/mSH_MCP_Spotlight_SXXXXX.pdf" },
        { name: "MPC Weekly Scorecard #Reports", url: "https://portaldoctool.cvs.com/rxreports/mpc/weekly/mPC_Scorecard_SXXXXX.pdf" },
        { name: "OPI (Operational Insights) #Reports", url: "https://portaldoctool.cvs.com/portalDocTool/viewDocuments.do?listingID=complianceModReports&roles=myReports&deptType=RX&metricID=storeXXXXX" },
        { name: "IER Monthly Scorecard #Reports ", url: "https://portaldoctool.cvs.com/retailportalfiles/business/iermonthlyscorecards/IER_Monthly_Scorecard_SXXXXX.pdf" },
        { name: "Central Fill Homepage #Pet Med/CF/SPAR", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Central_Fill_Homepage_20240206170244882.pdf" },
        { name: "POS Modernization/Register Update #IT Resources ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/POS_Mod_Landing_Page_20260423145002918.pptx_2pdf.pdf" },
        { name: "Rx/iO Update Homepage   #IT Resources", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/RxOS_Homepage_20250610161035278.pdf" },
        { name: "Virtual Verification Homepage #ID Resources", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Virtual_Verification_RxNet_Landing_Page.pdf" },
        { name: "Corp\Domain Apps Portal (Citrix) ", url: "https://remote.cvscaremark.com/Citrix/remotecorpWeb/" },
        { name: "CSOS Central POA  (Power of Attorney) #Regulatory ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/DEA_Central_CSOS_POA_Documents-_Group_A_20251210140954632.pdf" },
        { name: "CSOS Registrant Exhibit A list (Power of Attorney)   #Regulatory ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Exhibit_A_Retail_Registrants_2025_-_Group_A.pdf" },
        { name: "Print PIC POAs (Non-CSOS Power of Attorney)  #Regulatory ", url: "https://portaldoctool.cvs.com/retailportalfiles/business/rx/POA_XXXXX.pdf" },
        { name: "SpokenRx #Miscellaneous", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/store/oth/SpokenRx_myDocs_LandingePage.pptx_2pdf.pdf" },
        { name: "LearnRx Tracking #New Hires", url: "https://aetna.quickbase.com/nav/app/bstr5x75e/action/appoverview" },
        { name: "New Hire Password Setup Job Aid #New Hires", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Retail_New_Colleague_Password_Guide_20250820162352262.pdf" },
        { name: "Calculator #Operational ", url: "https://ti84hub.com/?embed=true" },
        { name: "Novavax #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/COVID_Novavax_Quick_Reference_9.17_FINAL_20250919151950379.pdf" },
        { name: "IMZ Ordering Portal   #Immunizations ", url: "https://ciim.rx.cvs.com/rx-coa/#/iit/login?store=FACILITY_ID" },
        { name: "Compliance Signage #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/oth/Compliance_Sustainability_RX_Signage_Review_File.pdf" },
        { name: "Yahoo (Google search alternative when it wont load...) ", url: "https://yahoo.com" },
        { name: "DuckDuckGo (Google search alternative when it wont load...) ", url: "https://duckduckgo.com" },
        { name: "Calendar #Operational", url: "/rxnet/calendar" },
        { name: "Compliance and RxC Shutoff Reporting (Field)  #Reports", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/oth/R%26C_Training_Resource_Page.pptx_2pdf.pdf" },
        { name: "FS @ Rx Attestation  #Training", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/FS_at_Rx_POS_Attestation_Tracker_20250930135204234.pdf" },
        { name: "COVID Vaccine Master Reference  #COVID", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/COVID-19_Vaccine_State_Guideline_and_Talking_Points_Job_Aid_20250827185139490.pdf" },
        { name: "Zipline  #Operational", url: "https://cvs.retailzipline.com/field/dashboard" },
        { name: "PA Clinical Labratory License/Certificate Reprint   #Regulatory", url: "https://www.palabsbillpayment.health.pa.gov/Home.aspx" },
        { name: "Zipline (Field) #Operational", url: "https://federatione.cvs.com/affwebservices/public/saml2sso?SPID=cvshealthsp_png_cvscom&RelayState=https://authsvc.cvshealth.com/idp/startSSO.ping?PartnerSpId=https://cvs.retailzipline.com/sso/saml/metadata/?SUBSTITUTE_STORE_NUMBER=XXXXX" },
        { name: "Rx Transfer Request Job Aid #Miscellaneous", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/RxTransferJobAid_20251216160319603.pdf" },
        { name: "MTC - Roster Readiness/Guidelines #Reports", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/rpt/RGLandingPage.pdf" },
        { name: "MTC - Weekly Report #Reports", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/oth/mTC_Weekly_STORE.xlsx_2pdf.pdf" },
        { name: "Weekly TempAlert Compliance Report #Reports", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/rpt/Store_Chainwide_TempAlert_Engagement_Reporting.xlsx_2pdf.pdf" },
        { name: "MPC Colleague Level Report #Reports", url: "https://portaldoctool.cvs.com/rxreports/mpc/weekly/CLR_Weekly/Colleague_Level_Reporting_Weekly_SXXXXX.pdf" },
        { name: "Multi-factor authentication (NEW)  #Human Resources ", url: "https://mfa.cvshealth.com/myaccount/" },
        { name: "Nebulizers/Spacers (NEW) #Dispensing", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Nebulizer_Dispensing_Job_Aid_2025_10_29_20251110134417326.pdf" },
        { name: "PingID Setup   #Human Resources ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/oth/Ping_Mobile_Registration_External_Network_from_Personal_Device.pdf" },
        { name: "DSCSA Full Functionality Job Aid  #Inventory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/DRAFT_DSCSA_Full_Functionality_Job_Aid_for_Pilot_Stores_20251522163222156.pdf" },
        { name: "DSCSA Quarantine Job Aid  #Inventory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/CFRx_DSCSA_Quarantine_Delivery_Check-In_Workflow_10302025_20251030153056926.pdf" },
        { name: "DSCSA Delivery Check-in Job Aid  #Inventory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/DRAFT_DSCSA_Full_Functionality_Job_Aid_for_Pilot_Stores_20251522163222156.pdf" },
        { name: "DSCSA Quick Guide  #Inventory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Delivery_Check-In_Expectations_Quick_Guide_20230113165419628.pdf" },
        { name: "StartSmart Facilitator Guide  #New Hires", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/SmartStart_Facilitator_Guide_20250808150140318.pdf" },
        { name: "StartSmart FAQs  #New Hires", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/StartSmart_FAQ_20250917112917976.pdf" },
        { name: "StartSmart Job Aid  #New Hires", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/StartSmart_Job_Aid_20250922145418800.pdf" },
        { name: "StartSmart Participant Guide  #New Hires", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/SmartStart_Participant_Guide_20250808144624526.pdf" },
        { name: "Electronic Signature Portal #Regulatory", url: "https://rxdw-esignature-store.rxdw-cld-ap.cvshealthcloud.com/GetSMEsigStore.do?method=perform&StoreNum=XXXXX" },
        { name: "Clinical Pharmacology Remote Access Setup Link", url: "https://www.clinicalkey.com/pharmacology/login?promoCodeGroup=DID416516&promoCode=416516&associatingWith=CVS%20Co,%20General%20Access" },
        { name: "Zipline - myTasks View", url: "https://cvs.retailzipline.com/field/my_tasks" },
        { name: "Bowel Prep Billing Tips #Dispensing", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Proper_Billing_of_Bowel_Preps_2025_%282%29_20251126141806523.pdf" },
        { name: "PA Technician Licensure", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Pennsylvania_Incumbent_Pharmacy_Technician_Application_Checklist_2025120917021865.pdf" },
        { name: "Print Most Recent Pharmacy License Issuance #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/wlm_task_reports/RX_LICENSE_XXXXX.pdf" },
        { name: "AP Store Visit Tool (SVT) Job Aid #Asset Protection ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/AP_SVT_-_FS_and_RX_Store_Leader_Dashboards_Guide_20260107141856115.pptx_2pdf.pdf" },
        { name: "CPR Class Scheduling #Immunizations", url: "https://c0axa109.caspio.com/dp/731b1000a87a77ff9fd24b08b4ac" },
        { name: "Training Managment System (TMS) #Reports", url: "https://tms.cvs.com/apps_dir_sm/tms2/index.cfm" },
        { name: "New AP/LP Store Visit Tool #Asset Protection", url: "https://ldp.cvsapps.com/sso" },
        { name: "Former Colleagues   #Human Resources", url: "https://alumnizone.cvs.com/alumnizone" },
        { name: "Roster Readiness / myTeam Roster Planning Tool #Manager", url: "/rxnet/docs/rosterreadiness.pdf" },
        { name: "IMZ Quick Reference  #Immunications", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/IMZ_Clinical_%26_Safety_Resource_Landing_Page-_QRGs_%26_CDC_2025062513344230.pptx_2pdf.pdf" },
        { name: "myInsights #Miscellaneous", url: "https://cvs.crowdicity.com/" },
        { name: "CFRx FAQ #Inventory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/CFRx_FAQs_WG_RB_07142022.pdf" },
        { name: "CFRx Ordering Guide #Inventory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/CFRx_Warehouse_%26_Outside_Vendor_Ordering_Guide_20250912115922886.pptx_2pdf.pdf" },
        { name: "CFRx Order Adjustments Job Aid #Inventory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Order_Adjustments_20230130142641714.pdf" },
        { name: "FlavoRx Recipe Generator Website #Compounding", url: "https://flavorxflavors.com/account/login.aspx?ReturnPage=%2fgenerator.aspx" },
        { name: "AP Store Leader Resources #Asset Protection", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/AP_Resources_%2526_Job_Aids_-_Store_Leaders_20260116151815753.pptx_2pdf.pdf" },
        { name: "RSSC Helpdesk Self Service  ", url: "https://colleaguezone.cvs.com/cz?id=sc_cat_item&table=sc_cat_item&sys_id=e3625b74fb221610b562f42bbeefdc58&recordUrl=com.glideapp.servicecatalog_cat_item_view.do%3Fv%3D1&sysparm_id=e3625b74fb221610b562f42bbeefdc58x" },
        { name: "Print PSE Certificate Job Aid  #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/PRINTING_A_PSE_CERTIFICATE_updated_20241227113233927.pdf" },
        { name: "Target Floater Certification  #Human Resources", url: "https://colleaguezone.cvs.com/cz?id=cz_people_leader_services" },
        { name: "Print CPR Certificate  #Immunizations", url: "https://resources.cardiopartners.com/page50/" },
        { name: "Uniform Ordering  #Manager", url: "https://cvstracking.hpidirectstore.net/?saml_sso" },
        { name: "LearnRx Guide  #New Hires", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/LearnRx_2.0_Resource_Page_20230320172428811.pptx_2pdf.pdf" },
        { name: "CFRx Order Check-In Job Aid #Inventory ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Delivery_CheckIn_Standalone_06282022_20230110190051769.pdf" },
        { name: "Values in Action  #Manager #Human Resources", url: "https://cvs.achievers.com" },
        { name: "Generic Substitution Signage  #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/D10647RX16_Compliance_PA_BiosimilarSign_%28003%29_2021081014032909_20221118093014786.pdf" },
        { name: "Naloxone Signage  #Required Docs", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/NaloxoneSign_2019_20190514111434617_20221118092845263.pdf" },
        { name: "ScriptPro Cleaning Log #Required Docs ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/ScriptPro_Maintenance_Schedule_Log_20260213092753871.pdf" },
        { name: "Kirby Cleaning Log #Required Docs ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/KL_Countertop_Cleaning_and_Calibration_Log_20241217123110219.pdf" },
        { name: "Top 200 Drugs Signage #Required Docs ", url: "/rxnet/docs/Top200.pdf" },
        { name: "Liquid medication with stock bottle BUD expiration chart  #Required Docs", url: "/rxnet/docs/BUD%20stock%20bottles.pdf" },
        { name: "No Smoking Sign  #Required Docs", url: "/rxnet/docs/No%20Smoking%20English%20Color.pdf" },
        { name: "Biometrics/Facial Recognition Scan #Biometrics ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Facial_Scan_Biometrics_-_Quick_Reference_Guide_%285%29_20250617114810499.pdf" },
        { name: "CFRx Outside Vendor (OV) Returns  #Inventory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/OV_Return_%C2%96_SystemGenerated_FebruaryVersion_20240329123432484.pptx_2pdf.pdf" },
        { name: "Warehouse/Distribution Center Delivery Job Aid  #Inventory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/perm/fm/oth/DC_Delivery_Job_Aid_Master.pdf" },
        { name: "Ecosia (Google search alternative when it wont load...)  ", url: "https://www.ecosia.org" },
        { name: "GLP-1 Adherence #Clinical ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/PCC_P4P_Adherence_Focus_jobaid_Pick_Up_Now_v4_20260325133410650.pdf" },
        { name: "Waiting Bin Inventory FAQs  #Miscellaneous", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Waiting_Bin_Inventory_Tips_and_Tricks_-_Updated%5B2%5D_20231221152654526.docx_2pdf.pdf" },
        { name: "State Specific Technician Licensing Master Guide  #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/CVS_Pharmacy_Technician_and_Unlicensed_Personnel_Guide_20240102095358844_%2812%29_20260213135146707.pdf" },
        { name: "Controlled Substance Early Fill Job Aid #Regulatory ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Early_Fill_Job_Aid_20260416171014384.pdf" },
        { name: "Controlled Substance Scheduling Fill Job Aid  #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/CS_Scheduling_Job_Aid_20260211164335417.pdf" },
        { name: "COVID Testing/RPh Prescribing LearningHub Module Training Guide #COVID ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Pharmacist_Testing_%26_Prescribing_LearningHub_Training_updated_Nov_2025_20251103163913693.docx_2pdf.pdf" },
        { name: "Medicare Part B Billing Landing Page  #Dispensing", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Medicare_Part_B_Landing_Page_20240729113534498.pptx_2pdf.pdf" },
        { name: "Medicare Part B Billing myWork Guide  #Dispensing", url: "/docs/medbmywork.pdf" },
        { name: "AP Operational Risk Metrics  #Asset Protection", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/2026_Asset_Protection_Operational_Risks_20260116135056794.pdf" },
        { name: "Workers' Compensation Procedure  #Human Resources", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/WorkersCompensationProcedures_20260427120218993.pdf" },
        { name: "Vacuum Ordering, Maintinence, and Supplies ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/service_channel_job_aid___Vacuums_2023041210230004.pdf" },
        { name: "Lilly Cold Chain Product Temperature Excursion Evaluation Tool #Clinical ", url: "https://tempex.lilly.com/us/" },
        { name: "Novo Nordisk Cold Chain Product Temperature Excursion Evaluation Tool #Clinical ", url: "https://virtual.mi-owi.com/mi/calculator" },
        { name: "CII Incremental/Partial Fills CVS Policy Document #Regulatory ", url: "https://policy.corp.cvscaremark.com/cs/groups/public/@pnp/@all/@7110/documents/sop/chat/mdg3/%7Eedisp/ropp-087714.pdf" },
        { name: "CII Incremental/Partial Fills Law Document #Regulatory ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/21_CFR_1306.13_%28up_to_date_as_of_2-20-2026%29_20260224154819718.pdf" },
        { name: "Lebanon Hiring Site  ", url: "https://sites.google.com/view/cvs-hiring-lebanon-pa/home" },

        { name: "RxConnect Compliance Reactivation  #Regulatory  ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/RxConnect_Access_Validation_Overview_2024090415191751.pdf" },

        { name: "IAM Portal #Human Resources  ", url: "https://idmgmt.cvshealth.com/iam-selfserviceportal-oci/home" },
        { name: "IMZ Status Report #Immunizations  ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Curriculum_for_IMZ_Immunizer_Status_Report_Job_Aid__2024041813265361.pdf" },
        { name: "Engagement Survey (Colleague Voices) #Human Resources ", url: "https://voices.cvshealth.com/" },
        { name: "BSwift Benefits Portal Manual Login (FYI password does not sync, you'll likely need to use forgot password)  ", url: "https://cvshealthbenefits.bswift.com/" },
        { name: "BSwift Benefits Portal Direct Login  ", url: "https://authsvc.cvshealth.com/idp/startSSO.ping?PartnerSpId=SP_Ping_SM_Bridge&TargetResource=https://federatione.cvshealth.com/affwebservices/public/saml2sso?SPID=secure.bswift.com" },
        { name: "Focal Performance Review Ratings Distribution Guidelines  #Human Resources  ", url: "https://colleaguezone.cvs.com/cz?id=kb_article&sysparm_article=KB0062056" },
        { name: "NIOSH Handling and Supplies #Regulatory  ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/USP_800_myDocs_Page_112023_2023112010251754.pdf" },
        { name: "Warfarin Stock Bottle Disposal #Regulatory  ", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Empty_Warfarin_Bottle_Management_20240228180255110.pdf" },
        { name: "Sharps Disposal (PA)  #Required Docs  ", url: "https://www.pa.gov/content/dam/copapwp-pagov/en/health/documents/topics/documents/opioids/Sharps%20Disposal%20Tips.pdf" },
        { name: "Clinical Pharmacology NDC Search #Clinical", url: "https://www.clinicalkey.com/pharmacology/find-by/ndc?ndc=ZZZZZZZZZZZ" },
        { name: "Workday Candidate Pipeline #Human Resources ", url: "https://www.myworkday.com/cvshealth/d/task/3005$3943.htmld" },
        { name: "The Heart Collection Apparel Store #Operational ", url: "https://www.thecvsheartcollection.com/theheartcollection/shop/apparel" },
        { name: "Solitaire #Admin", url: "/rxnet/solitaire" },
        { name: "Tetris #Admin", url: "/rxnet/tetris" },
        { name: "Pacman #Admin", url: "/rxnet/pacman" },
        { name: "Spark (External/Field) #Admin", url: "https://retailspark-aetnao365.msappproxy.net" },
        { name: "Spark (External/Field - Store Specific) #Admin", url: "https://retailspark-aetnao365.msappproxy.net/spark?view=storeView&storeName=sXXXXXrxs" },
        { name: "mySchedule Legacy/SAML SSO Login #Admin", url: "https://federatione.cvs.com/siteminderagent/forms/enterpriselogin.fcc?TYPE=33554433&REALMOID=06-000b85c2-7455-17b6-bef3-f8a50a5ca09e&GUID=&SMAUTHREASON=0&METHOD=GET&SMAGENTNAME=-SM-4qv8ej3I%2bef50jOTXBfzddyxWLgCk4rIl4aQ5C1Iv8Cpj7PHBvrt2ao8JPl1Sd7S&TARGET=-SM-HTTPS%3a%2f%2ffederatione%2ecvs%2ecom%2fsiteminderagent%2fredirectjsp%2fredirect%2ejsp%3fSPID%3dcvshealthsp_png_cvscom%26RelayState%3dhttps%3a%2f%2fcvs%2ereflexisinc%2ecom%2fkernel%2fviews%2fauthenticate%2fweb%2fCVS%2eview%26SMPORTALURL%3dhttps-%3A-%2F-%2Ffederatione%2ecvs%2ecom-%2Faffwebservices-%2Fpublic-%2Fsaml2sso%26SAMLTRANSACTIONID%3d8f897c89--6a8931ff--f5e8b1b2--dd468af6--3b0c612e--6" },
        { name: "RSSC Help Desk Self Service Tool (new link) #IT Resources", url: "https://cvshealth.service-now.com/cz?id=sc_cat_item&sys_id=437c428f3bc73e544f812964c3e45ac6&sysparm_category=2ad34ff01bdf2c10ba5b77761a4bcb83&catalog_id=e0d08b13c3330100c8b837659bba8fb4" },
        { name: "Ped Meds Homepage  #Pet Meds/CF/SPAR", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/Pet_Med_Resource_Page.pdf" },
        { name: "Sign Ordering Form  #Manager", url: "https://www.cognitoforms.com/LSI8/CVSGraphicsOrderForm" },
        { name: "Uniform Ordering Size Guide  #Manager", url: "https://cvstracking.hpidirectstore.net/images/store_images/Uniform_Sizing_Guide.pdf" },
        { name: "APhA Immunization Certification Reprint Job Aid  #Immunizations", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/APhA_IMZ_Training_Cert_Guide_20241114165913892.pptx_2pdf.pdf" },
        { name: "State Immunization LearningHub Modules Landing Page  #Training  #Immunizations", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/State_IMZ_Landing_Page__v2_20241114170446105.pptx_2pdf.pdf" },
        { name: "1-Source Credentialing Guide  #Immunizations", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/1-Source_Credential_Gap_Resolution_Guide_02132026_Pilot_20260303133039815.docx_2pdf.pdf" },
        { name: "LearnRPh Grad Intern Guide  #Training", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/LearnRPh_Intern_Program_Guide_Jan26_20260604111534407.pdf" },
        { name: "LearnRPh Grad Intern FAQs  #Training", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/DL_Grad_Job_Aid_Tracker%2C_Payroll%2C_Promo_2026_20260603171139319.pdf" },
        { name: "Report Regulatory Visit Job Aid  #Regulatory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Store_Steps_to_Report_a_State_Agency_Interaction_20260528135451320.pptx_2pdf.pdf" },
        { name: "GLP Landing Page  #Dispensing", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Landing_page_GLPONE.pdf" },
        { name: "GLP Check-in Job Aid  #Inventory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/store/OV_Check-in_Package_Scanning_Job_Aid_06152026_20260615162137473.pdf" },
        { name: "Cycle Count Enhancement Job Aid  #Inventory", url: "https://portaldoctool.cvs.com/retailportalfiles/radar_store/temp/fm/Cycle_Count_Enhancement_Job_Aid_June_2026_20260617135925591.pptx_2pdf.pdf" },
        { name: "XXXXXXXXXXXXXXX  #XXXXXXXXXX", url: "XXXXXXXXXXXXXXX" },
        { name: "XXXXXXXXXXXXXXX  #XXXXXXXXXX", url: "XXXXXXXXXXXXXXX" },

        
        
        
        { name: "CVS\Domain Apps Portal (Citrix) ", url: "https://remote.cvshealth.com/Citrix/remotecvsWeb/" }

];

